server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true

akmj:
  simple-api-server:
    url: ${SIMPLE_API_SERVER_URL:http://localhost:8889/simple}

cloud:
  aws:
    s3:
      bucket: fake-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ACCESSKEY
      secretKey: SECRETKEY
      instance-profile: true
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error